// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfdnajqylfkhvcnutacr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmZG5hanF5bGZraHZjbnV0YWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTUwNzcsImV4cCI6MjA1NzY5MTA3N30.8tzMjhA-kwvPgGIOlBrqVpbqWlZhKhm23-8iqD0sbgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);